import fs from 'node:fs';
import path from 'node:path';
import YAML from 'yaml';
import { COLOR_ROLES, SHADOW_ROLES, type ColorRole } from '../src/roles';

export interface ThemeMeta {
  id: string;
  label: string;
  colorScheme: 'light' | 'dark';
  extends?: string;
}

export interface ThemeFiles {
  meta: ThemeMeta;
  colors: Record<ColorRole, string>;
  effects: {
    glass: { blur: string };
    shadow: Record<(typeof SHADOW_ROLES)[number], string>;
  };
  spacing: Record<string, string>;
  typography: Record<
    string,
    {
      fontSize: string;
      lineHeight: string;
      fontWeight: string;
      letterSpacing?: string;
    }
  >;
  radius: Record<string, string>;
  icons: {
    brand: string;
    nav: Record<string, string>;
    category: Record<string, string>;
  };
}

const PACKAGE_ROOT = path.resolve(__dirname, '..');
const THEMES_DIR = path.join(PACKAGE_ROOT, 'themes');
const GENERATED_DIR = path.join(PACKAGE_ROOT, 'generated');

function readYamlFile<T>(filePath: string): T {
  return YAML.parse(fs.readFileSync(filePath, 'utf8')) as T;
}

export function listThemeIds(): string[] {
  return fs
    .readdirSync(THEMES_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

export function loadTheme(themeId: string): ThemeFiles {
  const themeDir = path.join(THEMES_DIR, themeId);
  const meta = readYamlFile<ThemeMeta>(path.join(themeDir, 'theme.meta.yaml'));

  if (meta.extends) {
    throw new Error(
      `Theme inheritance is not implemented yet (${themeId} extends ${meta.extends}).`,
    );
  }

  const colors = readYamlFile<Record<ColorRole, string>>(path.join(themeDir, 'colors.yaml'));
  const effects = readYamlFile<ThemeFiles['effects']>(path.join(themeDir, 'effects.yaml'));
  const spacing = readYamlFile<ThemeFiles['spacing']>(path.join(themeDir, 'spacing.yaml'));
  const typography = readYamlFile<ThemeFiles['typography']>(path.join(themeDir, 'typography.yaml'));
  const radius = readYamlFile<ThemeFiles['radius']>(path.join(themeDir, 'radius.yaml'));
  const icons = readYamlFile<ThemeFiles['icons']>(path.join(themeDir, 'icons.yaml'));

  validateTheme(themeId, colors, effects);

  return { meta, colors, effects, spacing, typography, radius, icons };
}

export function validateTheme(
  themeId: string,
  colors: Record<string, string>,
  effects: ThemeFiles['effects'],
): void {
  for (const role of COLOR_ROLES) {
    if (!colors[role]) {
      throw new Error(`Theme "${themeId}" is missing color role: ${role}`);
    }
  }

  for (const role of SHADOW_ROLES) {
    if (!effects.shadow[role]) {
      throw new Error(`Theme "${themeId}" is missing shadow role: ${role}`);
    }
  }

  if (!effects.glass?.blur) {
    throw new Error(`Theme "${themeId}" is missing effects.glass.blur`);
  }
}

export function buildThemeCss(themeId: string, theme: ThemeFiles): string {
  const lines: string[] = ['/* Generated by @freshy/theme — do not edit */', ''];

  const selector =
    themeId === 'default'
      ? `:root:not([data-theme='dark']),\n[data-theme='default']`
      : `[data-theme='${themeId}']`;

  lines.push(`${selector} {`);

  for (const role of COLOR_ROLES) {
    lines.push(`  --color-${role}: ${theme.colors[role]};`);
  }

  lines.push(`  --effect-glass-blur: ${theme.effects.glass.blur};`);

  for (const role of SHADOW_ROLES) {
    lines.push(`  --shadow-${role}: ${theme.effects.shadow[role]};`);
  }

  lines.push(`  color-scheme: ${theme.meta.colorScheme};`);
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

function toTsObject(value: unknown, indent = 0): string {
  const pad = '  '.repeat(indent);
  if (Array.isArray(value)) {
    const items = value.map((item) => `${pad}  ${toTsObject(item, indent + 1)},`).join('\n');
    return `[\n${items}\n${pad}]`;
  }
  if (value && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>).map(([key, nested]) => {
      const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`;
      return `${pad}  ${safeKey}: ${toTsObject(nested, indent + 1)},`;
    });
    return `{\n${entries.join('\n')}\n${pad}}`;
  }
  if (typeof value === 'string') {
    return JSON.stringify(value);
  }
  return String(value);
}

export function buildThemeTokensTs(themeId: string, theme: ThemeFiles): string {
  return `/* Generated by @freshy/theme — do not edit */
export const meta = ${toTsObject(theme.meta)} as const;

export const colors = ${toTsObject(theme.colors)} as const;

export const effects = ${toTsObject(theme.effects)} as const;

export const spacing = ${toTsObject(theme.spacing)} as const;

export const typography = ${toTsObject(theme.typography)} as const;

export const radius = ${toTsObject(theme.radius)} as const;

export const icons = ${toTsObject(theme.icons)} as const;
`;
}

export function buildIndexTs(themeIds: string[]): string {
  const imports = themeIds
    .map((id) => `import * as ${toImportId(id)} from './${id}.tokens';`)
    .join('\n');

  const registry = themeIds.map((id) => `  ${JSON.stringify(id)}: ${toImportId(id)},`).join('\n');

  return `/* Generated by @freshy/theme — do not edit */
${imports}

export const THEME_IDS = ${JSON.stringify(themeIds)} as const;
export type ThemeId = (typeof THEME_IDS)[number];

const themes = {
${registry}
} as const;

export type ThemeTokens = (typeof themes)[ThemeId];

export function getThemeTokens(themeId: ThemeId): ThemeTokens {
  return themes[themeId];
}

export function getDefaultThemeTokens(): ThemeTokens {
  return getThemeTokens('default');
}
`;
}

function toImportId(themeId: string): string {
  if (themeId === 'default') {
    return 'defaultTheme';
  }
  return themeId.replace(/[^a-zA-Z0-9_$]/g, '_');
}

function themeCompileOrder(themeIds: string[]): string[] {
  return [...themeIds].sort((a, b) => {
    if (a === 'default') return -1;
    if (b === 'default') return 1;
    return a.localeCompare(b);
  });
}

export function compileThemes(): string[] {
  const themeIds = themeCompileOrder(listThemeIds());
  fs.mkdirSync(GENERATED_DIR, { recursive: true });

  const cssChunks: string[] = [];

  for (const themeId of themeIds) {
    const theme = loadTheme(themeId);
    const css = buildThemeCss(themeId, theme);
    const tokensTs = buildThemeTokensTs(themeId, theme);

    fs.writeFileSync(path.join(GENERATED_DIR, `${themeId}.css`), css);
    fs.writeFileSync(path.join(GENERATED_DIR, `${themeId}.tokens.ts`), tokensTs);
    cssChunks.push(css);
  }

  fs.writeFileSync(path.join(GENERATED_DIR, 'themes.css'), cssChunks.join('\n'));
  fs.writeFileSync(path.join(GENERATED_DIR, 'index.ts'), buildIndexTs(themeIds));

  return themeIds;
}

if (require.main === module) {
  const ids = compileThemes();
  console.log(`Compiled themes: ${ids.join(', ')}`);
}
