#!/usr/bin/env bash
# Upload PR screenshots to Cloudflare R2 and output markdown for PR comment.
set -euo pipefail

SCREENSHOTS_DIR="${1:-screenshots}"
PR_NUMBER="${2:-}"

if [ ! -d "${SCREENSHOTS_DIR}" ]; then
  echo "No screenshots directory: ${SCREENSHOTS_DIR}"
  exit 0
fi

ACCOUNT_ID="${R2_ACCOUNT_ID:-}"
ACCESS_KEY="${R2_ACCESS_KEY_ID:-}"
SECRET_KEY="${R2_SECRET_ACCESS_KEY:-}"
BUCKET="${R2_BUCKET_NAME:-}"
PUBLIC_URL="${R2_PUBLIC_URL:-}"

MARKDOWN_FILE="${SCREENSHOTS_DIR}/pr-comment.md"
: > "${MARKDOWN_FILE}"

echo "## Freshy | Page previews" >> "${MARKDOWN_FILE}"
echo "" >> "${MARKDOWN_FILE}"
echo "| Screen | Preview |" >> "${MARKDOWN_FILE}"
echo "|--------|---------|" >> "${MARKDOWN_FILE}"

PAGES=(
  "explore:Freshy Map (Explore)"
  "cooling:Categories (Cooling)"
  "place-list:Place List (Category)"
  "place-detail:Place Details"
  "saved:Saved Places"
  "profile:My Profile"
)

r2_configured() {
  [ -n "${ACCOUNT_ID}" ] && [ -n "${ACCESS_KEY}" ] && [ -n "${SECRET_KEY}" ] && [ -n "${BUCKET}" ] && [ -n "${PUBLIC_URL}" ] && [ -n "${PR_NUMBER}" ]
}

if r2_configured; then
  ENDPOINT="https://${ACCOUNT_ID}.r2.cloudflarestorage.com"
  export AWS_ACCESS_KEY_ID="${ACCESS_KEY}"
  export AWS_SECRET_ACCESS_KEY="${SECRET_KEY}"
  export AWS_DEFAULT_REGION="auto"

  echo "Uploading screenshots to R2 bucket ${BUCKET}/ci/pr-${PR_NUMBER}/"
  for entry in "${PAGES[@]}"; do
    file="${entry%%:*}"
    label="${entry##*:}"
    src="${SCREENSHOTS_DIR}/${file}.png"
    if [ -f "${src}" ]; then
      dest="ci/pr-${PR_NUMBER}/${file}.png"
      aws s3 cp "${src}" "s3://${BUCKET}/${dest}" \
        --endpoint-url "${ENDPOINT}" \
        --content-type "image/png" \
        --quiet
      url="${PUBLIC_URL%/}/${dest}"
      echo "| ${label} | ![${label}](${url}) |" >> "${MARKDOWN_FILE}"
    fi
  done
else
  echo "> R2 not configured — download screenshots from the workflow **Artifacts** tab." >> "${MARKDOWN_FILE}"
  echo "" >> "${MARKDOWN_FILE}"
  for entry in "${PAGES[@]}"; do
    file="${entry%%:*}"
    label="${entry##*:}"
    if [ -f "${SCREENSHOTS_DIR}/${file}.png" ]; then
      echo "- **${label}**: \`${file}.png\`" >> "${MARKDOWN_FILE}"
    fi
  done
fi

echo "" >> "${MARKDOWN_FILE}"
echo "---" >> "${MARKDOWN_FILE}"
echo "*Generated by [CI workflow](.github/workflows/ci.yml)*" >> "${MARKDOWN_FILE}"

cat "${MARKDOWN_FILE}"
