#!/usr/bin/env bash
# Upload PR screenshots to GCS and output markdown for PR comment.
set -euo pipefail

SCREENSHOTS_DIR="${1:-screenshots}"
PR_NUMBER="${2:-}"

if [ ! -d "${SCREENSHOTS_DIR}" ]; then
  echo "No screenshots directory: ${SCREENSHOTS_DIR}"
  exit 0
fi

BUCKET="${GCS_BUCKET_NAME:-}"
PROJECT="${GCP_PROJECT_ID:-}"

MARKDOWN_FILE="${SCREENSHOTS_DIR}/pr-comment.md"
: > "${MARKDOWN_FILE}"

echo "## Freshy — Page previews" >> "${MARKDOWN_FILE}"
echo "" >> "${MARKDOWN_FILE}"
echo "| Screen | Preview |" >> "${MARKDOWN_FILE}"
echo "|--------|---------|" >> "${MARKDOWN_FILE}"

PAGES=(
  "explore:Mapa Freshy (Explore)"
  "cooling:Categorias (Cooling)"
  "place-detail:Detalhes do Local"
  "profile:Meu Perfil"
)

if [ -n "${BUCKET}" ] && [ -n "${PROJECT}" ] && [ -n "${PR_NUMBER}" ]; then
  echo "Uploading screenshots to gs://${BUCKET}/ci/pr-${PR_NUMBER}/"
  for entry in "${PAGES[@]}"; do
    file="${entry%%:*}"
    label="${entry##*:}"
    src="${SCREENSHOTS_DIR}/${file}.png"
    if [ -f "${src}" ]; then
      dest="ci/pr-${PR_NUMBER}/${file}.png"
      gcloud storage cp "${src}" "gs://${BUCKET}/${dest}" --quiet
      url="https://storage.googleapis.com/${BUCKET}/${dest}"
      echo "| ${label} | ![${label}](${url}) |" >> "${MARKDOWN_FILE}"
    fi
  done
else
  echo "> GCS not configured — download screenshots from the workflow **Artifacts** tab." >> "${MARKDOWN_FILE}"
  echo "" >> "${MARKDOWN_FILE}"
  for entry in "${PAGES[@]}"; do
    file="${entry%%:*}"
    label="${entry##*:}"
    if [ -f "${SCREENSHOTS_DIR}/${file}.png" ]; then
      echo "- **${label}**: \`${file}.png\`" >> "${MARKDOWN_FILE}"
    fi
  done
fi

echo "" >> "${MARKDOWN_FILE}"
echo "---" >> "${MARKDOWN_FILE}"
echo "*Generated by [CI workflow](.github/workflows/ci.yml)*" >> "${MARKDOWN_FILE}"

cat "${MARKDOWN_FILE}"
